[package]
name = "ci-deps"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
cargo-readme = "3.2.0"
action-validator = "0.8.0"
kani-verifier = "0.60.0"
cargo-nextest = "0.9.122"
cargo-llvm-cov = "0.6.24"